exclude:
  - portfolio/ 
#gems:
#  - jekyll-compass
#  - jemoji
#  - rmagick

#gallerytag:
#    dir: images/galleries
#    url: /images/galleries
#    thumb_width: 150
#    thumb_height: 150
    # columns: 4
